# Generated by Django 5.2.14 on 2026-06-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_web', '0005_alter_tiket_nomor_surat_pengantar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceTandaTerima',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(help_text='Tahun penerapan sequence', unique=True, verbose_name='Tahun')),
                ('nomor_terakhir', models.IntegerField(help_text='Nomor terakhir yang digunakan. Nomor berikutnya akan dimulai dari nilai ini + 1.', verbose_name='Nomor Terakhir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sequence Tanda Terima',
                'verbose_name_plural': 'Sequence Tanda Terima',
                'db_table': 'sequence_tanda_terima',
                'ordering': ['-tahun'],
            },
        ),
    ]
