from .home import *
from .notification import *
from .new_login import *
from .dashboard import *
from .kategori_ilap import *
from .ilap import *
from .jenis_data_ilap import *
from .jenis_tabel import *
from .kategori_wilayah import *
from .kanwil import *
from .kpp import *
from .status_data import *
from .dasar_hukum import *
from .status_penelitian import *
from .bentuk_data import *
from .cara_penyampaian import *
from .media_backup import *
from .klasifikasi_jenis_data import *
from .periode_pengiriman import *
from .periode_jenis_data import *
from .jenis_prioritas_data import *
from .pic import *
from .nama_tabel import *
from .durasi_jatuh_tempo import *
from .backup_data import *
from .tanda_terima_data import *
from .monitoring_penyampaian_data import *
from .docx_template import *
from .laporan_pengendalian_mutu import *
from .laporan_kelengkapan_data import *
from .tiket import *
from .laporan_pide_filter_options import *
from .laporan_transfer import *
from .laporan_sla_perekaman import *
from .laporan_sla_identifikasi import *
from .laporan_metrik_data_eksternal import *
